Title: Deterministic Behavior in Socket Addresses
URL: https://docs.python.org/3/library/socket.html
Summary: Using hostnames in socket addresses may lead to nondeterministic behavior due to varying DNS resolution results. To ensure deterministic behavior, it is recommended to use numeric addresses. All errors raise exceptions, primarily `OSError` or its subclasses, while non-blocking mode and timeouts can be managed through `setblocking()` and `settimeout()` methods, respectively.
---

If you use a hostname in the _host_ portion of IPv4/v6 socket address, the program may show a nondeterministic behavior, as Python uses the first address returned from the DNS resolution. The socket address will be resolved differently into an actual IPv4/v6 address, depending on the results from DNS resolution and/or the host configuration. For deterministic behavior use a numeric address in _host_ portion.
All errors raise exceptions. The normal exceptions for invalid argument types and out-of-memory conditions can be raised. Errors related to socket or address semantics raise [`OSError`](https://docs.python.org/3/library/exceptions.html#OSError "OSError") or one of its subclasses.
Non-blocking mode is supported through [`setblocking()`](https://docs.python.org/3/library/socket.html#socket.socket.setblocking "socket.socket.setblocking"). A generalization of this based on timeouts is supported through [`settimeout()`](https://docs.python.org/3/library/socket.html#socket.socket.settimeout "socket.socket.settimeout").
## Module contents[¶](https://docs.python.org/3/library/socket.html#module-contents "Link to this heading")
The module [`socket`](https://docs.python.org/3/library/socket.html#module-socket "socket: Low-level networking interface.") exports the following elements.
### Exceptions[¶](https://docs.python.org/3/library/socket.html#exceptions "Link to this heading") 

_exception_ socket.error[¶](https://docs.python.org/3/library/socket.html#socket.error "Link to this definition")
    
A deprecated alias of [`OSError`](https://docs.python.org/3/library/exceptions.html#OSError "OSError").
Changed in version 3.3: Following [**PEP 3151**](https://peps.python.org/pep-3151/), this class was made an alias of [`OSError`](https://docs.python.org/3/library/exceptions.html#OSError "OSError"). 

_exception_ socket.herror[¶](https://docs.python.org/3/library/socket.html#socket.herror "Link to this definition")
    
A subclass of [`OSError`](https://docs.python.org/3/library/exceptions.html#OSError "OSError"), this exception is raised for address-related errors, i.e. for functions that use _h_errno_ in the POSIX C API, including [`gethostbyname_ex()`](https://docs.python.org/3/library/socket.html#socket.gethostbyname_ex "socket.gethostbyname_ex") and [`gethostbyaddr()`](https://docs.python.org/3/library/socket.html#socket.gethostbyaddr "socket.gethostbyaddr"). The accompanying value is a pair `(h_errno, string)` representing an error returned by a library call. _h_errno_ is a numeric value, while _string_ represents the description of _h_errno_ , as returned by the `hstrerror()` C function.
Changed in version 3.3: This class was made a subclass of [`OSError`](https://docs.python.org/3/library/exceptions.html#OSError "OSError"). 

_exception_ socket.gaierror[¶](https://docs.python.org/3/library/socket.html#socket.gaierror "Link to this definition")
    
A subclass of [`OSError`](https://docs.python.org/3/library/exceptions.html#OSError "OSError"), this exception is raised for address-related errors by [`getaddrinfo()`](https://docs.python.org/3/library/socket.html#socket.getaddrinfo "socket.getaddrinfo") and [`getnameinfo()`](https://docs.python.org/3/library/socket.html#socket.getnameinfo "socket.getnameinfo"). The accompanying value is a pair `(error, string)` representing an error returned by a library call. _string_ represents the description of _error_ , as returned by the `gai_strerror()` C function. The numeric _error_ value will match one of the `EAI_*` constants defined in this module.
Changed in version 3.3: This class was made a subclass of [`OSError`](https://docs.python.org/3/library/exceptions.html#OSError "OSError").