Title: Python 3 Change Log - Bug Fixes
URL: https://docs.python.org/3/whatsnew/changelog.html
Summary: This section of the Python 3 change log highlights several bug fixes including resolving a crash in `email.utils.parsedate_tz()` due to `UnboundLocalError`, addressing quadratic behavior in the enum module during class creation, and correcting the output of `traceback.print_exc()` with specific `end_offset` settings.
---

/bugs.python.org/issue?@action=redirect&bpo=45239): Fixed [`email.utils.parsedate_tz()`](https://docs.python.org/3/library/email.utils.html#email.utils.parsedate_tz "email.utils.parsedate_tz") crashing with [`UnboundLocalError`](https://docs.python.org/3/library/exceptions.html#UnboundLocalError "UnboundLocalError") on certain invalid input instead of returning `None`. Patch by Ben Hoyt.
  * [bpo-45417](https://bugs.python.org/issue?@action=redirect&bpo=45417): Fix quadratic behaviour in the enum module: Creation of enum classes with a lot of entries was quadratic.
  * [bpo-45249](https://bugs.python.org/issue?@action=redirect&bpo=45249): Fix the behaviour of [`traceback.print_exc()`](https://docs.python.org/3/library/traceback.html#traceback.print_exc "traceback.print_exc") when displaying the caret when the `end_offset` in the exception is set to 0. Patch by Pablo Galindo
  * [bpo-45416](https://bugs.python.org/issue?@action=redirect&bpo=45416): Fix use of [`asyncio.Condition`](https://docs.python.org/3/library/asyncio-sync.html#asyncio.Condition "asyncio.Condition") with explicit [`asyncio.Lock`](https://docs.python.org/3/library/asyncio-sync.html#asyncio.Lock "asyncio.Lock") objects, which was a regression due to removal of explicit loop arguments. Patch by Joongi Kim.
  * [bpo-20028](https://bugs.python.org/issue?@action=redirect&bpo=20028): Empty escapechar/quotechar is not allowed when initializing [`csv.Dialect`](https://docs.python.org/3/library/csv.html#csv.Dialect "csv.Dialect"). Patch by Vajrasky Kok and Donghee Na.
  * [bpo-44904](https://bugs.python.org/issue?@action=redirect&bpo=44904): Fix bug in the [`doctest`](https://docs.python.org/3/library/doctest.html#module-doctest "doctest: Test pieces of code within docstrings.") module that caused it to fail if a docstring included an example with a `classmethod` `property`. Patch by Alex Waygood.
  * [bpo-45406](https://bugs.python.org/issue?@action=redirect&bpo=45406): Make [`inspect.getmodule()`](https://docs.python.org/3/library/inspect.html#inspect.getmodule "inspect.getmodule") catch `FileNotFoundError` raised by `inspect.getabsfile()`, and return `None` to indicate that the module could not be determined.
  * [bpo-45411](https://bugs.python.org/issue?@action=redirect&bpo=45411): Add extensions for files containing subtitles - .srt & .vtt - to the mimetypes.py module.
  * [bpo-10716](https://bugs.python.org/issue?@action=redirect&bpo=10716): Migrated pydoc to HTML5 (without changing the look of it). Side effect is to update xmlrpc’s `ServerHTMLDoc` which now uses the CSS too. cgitb now relies less on pydoc (as it can’t use the CSS file).
  * [bpo-27580](https://bugs.python.org/issue?@action=redirect&bpo=27580): Add support of null characters in [`csv`](https://docs.python.org/3/library/csv.html#module-csv "csv: Write and read tabular data to and from delimited files.").
  * [bpo-45262](https://bugs.python.org/issue?@action=redirect&bpo=45262): Prevent use-after-free in asyncio. Make sure the cached running loop holder gets cleared on dealloc to prevent use-after-free in get_running_loop
  * [bpo-45386](https://bugs.python.org/issue?@action=redirect&bpo=45386): Make [`xmlrpc.client`](https://docs.python.org/3/library/xmlrpc.client.html#module-xmlrpc.client "xmlrpc.client: XML-RPC client access.") more robust to C runtimes where the underlying C `strftime` function results in a `ValueError` when testing for year formatting options.
  * [bpo-20028](https://bugs.python.org/issue?@action=redirect&bpo=20028): Improve error message of [`csv.Dialect`](https://docs.python.org/3/library/csv.html#csv.Dialect "csv.Dialect") when initializing. Patch by Vajrasky Kok and Donghee Na.
  * [bpo-45343](https://bugs.python.org/issue?@action=redirect&bpo=45343): Update bundled pip to 21.2.4 and setuptools to 58.1.0
  * [bpo-45328](https://bugs.python.org/issue?@action=redirect&bpo=45328): Fixed [`http.client.HTTPConnection`](https://docs.python.org/3/library/http.client.html#http.client.HTTPConnection "http.client.HTTPConnection") to work properly in OSs that don’t support the `TCP_NODELAY` socket option.
  * [bpo-45243](https://bugs.python.org/issue?@action=redirect&bpo=45243): Add [`setlimit()`](https://docs.python.org/3/library/sqlite3.html#sqlite3.Connection.setlimit "sqlite3.Connection.setlimit") and [`getlimit()`](https://docs.python.org/3/library/sqlite3.html#sqlite3.Connection.getlimit "sqlite3.Connection.getlimit") to [`sqlite3.Connection`](https://docs.python.org/3/library/sqlite3.html#sqlite3.Connection "sqlite3.Connection") for setting and getting SQLite limits by connection basis. Patch by Erlend E. Aasland.
  * [bpo-45320](https://bugs.python.org/issue?@action=redirect&bpo=45320): Removed from the [`inspect`](https://docs.python.org/3/library/inspect.html#module-inspect "inspect: Extract information and source code from live objects.") module:
    *